// SoE Companion item lists for Holy Grail tracking
// Refreshed from The Archivist SoE wiki Uniques.json on 2026-05-14.
// STATIC_UNIQUE_ITEMS contains non-Hellforged unique items.
// STATIC_HELLFORGED_UNIQUE_ITEMS contains Hellforged unique variants.
// STATIC_SET_ITEMS contains set item piece names from the existing SoE data source.
export const STATIC_UNIQUE_ITEMS = [
  "Abyssal Ward", "Achilles Strike", "Aetherwing", "Aidan's Scar",
  "Akarat's Devotion", "Akarat's Rage", "Alma Negra", "Amalgamation",
  "Andariel's Visage", "Annihilus", "Anvilguard Strap", "Arachnid Mesh",
  "Arioc's Needle", "Arkaine's Valor", "Arm of King Leoric", "Armageddon's Blade",
  "Arreat's Face", "Askaris Zephyr", "Astramentis", "Astreon's Iron Ward",
  "Athena's Wrath", "Atma's Scarab", "Atma's Wail", "Axe of Fechmar",
  "Azurewrath", "Baezil's Vortex", "Balefire", "Band of Skulls",
  "Bane Ash", "Bannerlord's Call", "Baranar's Star", "Bartuc's Cut-Throat",
  "Basilisk's Quill", "Biggin's Bonnet", "Bing Sz Wang", "Black Hades",
  "Blackbog's Sharp", "Blackhand Key", "Blackhorn's Face", "Blackleach Blade",
  "Blackoak Shield", "Blacktongue", "Blade of Ali Baba", "Bladebone",
  "Bladebuckle", "Blastbark", "Blinkbat's Form", "Blood Crescent",
  "Blood Raven's Charge", "Bloodfist", "Bloodletter", "Bloodmoon",
  "Bloodrise", "Bloodthief", "Bloodtree Stump", "Boneflame",
  "Boneflesh", "Bonehew", "Boneshade", "Boneslayer Blade",
  "Bonesnap", "Brainhew", "Brimstone Rain", "Bul-Kathos' Wedding Band",
  "Buriza-Do Kyanon", "Butcher's Pupil", "Bverrit Keep", "Cage of the Unsullied",
  "Cain's Wisdom", "Call of the Brotherhood", "Carin Shard", "Carrion Wind",
  "Cerebus' Bite", "Chance Guards", "Chromatic Ire", "Cliffkiller",
  "Cloudcrack", "Coif of Glory", "Coldkill", "Coldsteel Eye",
  "Constricting Loop", "Corpsemourn", "Crackleshot", "Crainte Vomir",
  "Cranebeak", "Crescent Moon", "Crow Caw", "Crown of Ages",
  "Crown of Thieves", "Crushflange", "Culwen's Point", "Cyclopean Roar",
  "Dark Abyss", "Dark Clan Crusher", "Darkforce Spawn", "Darkglow",
  "Darksight Helm", "Death Cleaver", "Death's Fathom", "Death's Poise",
  "Death's Web", "Deathbit", "Deathspade", "Defiance of Destiny",
  "Demon Limb", "Demon Machine", "Demon's Arch", "Demonhorn's Edge",
  "Denmother", "Dimoak's Hew", "Djinn Slayer", "Doom's Finger",
  "Doombringer", "Doomslinger", "Dracul's Grasp", "Dragonscale",
  "Duriel's Shell", "Duskdeep", "Dwarf Star", "Eaglehorn",
  "Earth Shifter", "Earthshaker", "Ebonbane", "Empowered Spirit",
  "Endlesshail", "Eschuta's Temper", "Ethereal Edge", "Executioner's Justice",
  "Fallen Gardens", "Fara's Reminiscence", "Fara's Remorse", "Fara's Resentment ",
  "Felloak", "Fenris", "Firelizard's Talons", "Flamebellow",
  "Fleshrender", "Fleshripper", "Fluid Motion", "Frostburn",
  "Frostwind", "Frozen Sorrow", "Gargoyle's Bite", "Gaze of the Abyss",
  "Gerke's Sanctuary", "Gheed's Fortune", "Ghostflame", "Ghoulhide",
  "Giant Skull", "Gimmershred", "Ginther's Rift", "Glacial Tempest",
  "Gleamscythe", "Gloom's Trap", "Goblin Toe", "Goldrim",
  "Goldskin", "Goldstrike Arch", "Goldwrap", "Gore Rider",
  "Gorefoot", "Goreshovel", "Gravenspine", "Gravepalm",
  "Greyform", "Griffon's Eye", "Grim's Burning Dead", "Griswold's Edge",
  "Guardian Angel", "Guardian Naga", "Gull", "Gut Siphon",
  "Hadriel's Hand", "Hailstorm", "Halaberd's Reign", "Halo of the Justicar",
  "Hand of Blessed Light", "Harlequin Crest", "Hawkmail", "Head Hunter's Glory",
  "Headhunter", "Headstriker", "Heart Carver", "Heaven's Light",
  "Heavenly Garb", "Hellcast", "Hellclap", "Hellfire Torch",
  "Hellmouth", "Hellplague", "Hellrack", "Hellslayer",
  "Herald of Zakarum", "Hexfire", "Highlord's Wrath", "Homunculus",
  "Hone Sundan", "Horadrim Almanac", "Horadrim Navigator", "Horizon's Tornado", "Hotspur", "Howltusk",
  "Humongous", "Husoldal Evo", "Iceblink", "Ichorsting",
  "Imperial Palace", "Indigon", "Infernostride", "Iron Pelt",
  "Ironstone", "Islestrike", "Itherael's Path", "Jade Talon",
  "Jalal's Mane", "Kalan's Legacy", "Kashyas Sorrow", "Kelpie Snare",
  "Kinemil's Awl", "Kira's Guardian", "Knell Striker", "Kratos Fury",
  "Kuko Shakaku", "Lacerator", "Lance Guard", "Lance of Yaggai",
  "Langer Briser", "Lava Gout", "Leadcrow", "Lenymo",
  "Leoric's Mithril Bane", "Leviathan", "Lidless Wall", "Lightsabre",
  "Lycander's Aim", "Lycander's Flank", "Maelstrom", "Mage Slayer",
  "Mageblood", "Magefist", "Magewrath", "Manald Heal",
  "Manastorm", "Mang Song's Lesson", "Mara's Kaleidoscope", "Marrowwalk",
  "Martyrdom", "Medusa's Gaze", "Melding of the Flesh", "Merman's Sprocket",
  "Messerschmidt's Reaver", "Metalgrid", "Mjölner", "Moonfall",
  "Moser's Blessed Circle", "Nagelring", "Nature's Peace", "Nightsmoke",
  "Nightwing's Veil", "Nihlathak's Malice", "Nokozan Relic", "Nord's Tenderizer",
  "Nosferatu's Coil", "Occultist", "Odium", "Ondal's Wisdom",
  "One With Nothing", "Original Sin", "Ormus' Robes", "Outer Void",
  "Overlord's Helm", "Peasant Crown", "Pelta Lunata", "Pierre Tombale Couant",
  "Plague Bearer", "Pluckeye", "Pompeii's Wrath", "Progenesis",
  "Purgatory", "Pus Spitter", "Que-Hegan's Wisdom", "Quetzalcoatl",
  "Radament's Sphere", "Raekor's Virtue", "Rainbow Facet", "Rakescar",
  "Ramfodder", "Rathma's Stygian Hand", "Rattlecage", "Raven Claw",
  "Raven Frost", "Ravenlore", "Razor's Edge", "Razorswitch",
  "Razortail", "Razortine", "Ribcracker", "Riphook",
  "Ripsaw", "Rixot's Keen", "Rockfleece", "Rockstopper",
  "Rogue's Bow", "Rune Master", "Rusthandle", "Sacred Totem",
  "Sanctuary's Demise", "Sandstorm Trek", "Sankekur's Fall", "Saracen's Chance",
  "Schaefer's Hammer", "Seraph's Hymn", "Serpent Lord", "Seven-League Step",
  "Shadow Dancer", "Shadow Killer", "Shadowfang", "Shaftstop", "Skeleton Key",
  "Shatterblade", "Shatterhead", "Siggard's Staunch", "Silks of the Victor",
  "Silkweave", "Skewer of Krintiz", "Skin of the Flayed One", "Skin of the Vipermagi",
  "Skorn", "Skull Collector", "Skull Splitter", "Skullder's Ire",
  "Skystrike", "Skywarden", "Snakecord", "Snowclash",
  "Soul Drainer", "Soul Harvest", "Soulfeast Tine", "Soulflay",
  "Sparking Mail", "Spectral Shard", "Spellsteel", "Spike Thorn",
  "Spineripper", "Spire of Honor", "Spire of Lazarus", "Spirit Forge",
  "Spirit Keeper", "Spirit Ward", "Stalker's Cull", "Stealskull",
  "Steel Carapace", "Steel Pillar", "Steel Shade", "Steelclash",
  "Steeldriver", "Steelgoad", "Steelrend", "Stone Crusher",
  "Stoneraven", "Stormchaser", "Stormeye", "Stormguild",
  "Stormlash", "Stormrider", "Stormshield", "Stormspike",
  "Stormspire", "Stormstrike", "Stoutnail", "String of Ears",
  "Suicide Branch", "Sureshrill Frost", "Swiftwind Needle", "Swordback Hold",
  "Swordguard", "Tarnhelm", "Tearhaunch", "Tempered Flesh",
  "Tempest", "Templar's Might", "Temporalis", "The Atlantean",
  "The Battlebranch", "The Cat's Eye", "The Centurion", "The Chieftain",
  "The Cranium Basher", "The Diggler", "The Dragon Chang", "The Eye of Etlich",
  "The Face of Horror", "The Fetid Sprinkler", "The Gavel of Pain", "The General's Tan Do Li Ga",
  "The Gladiator's Bane", "The Gnasher", "The Grandfather", "The Grim Reaper",
  "The Hand of Broc", "The Impaler", "The Iron Jang Bong", "The Jade Tan Do",
  "The Mahim-Oak Curio", "The Meat Scraper", "The Minotaur", "The Oculus",
  "The Oppressor", "The Patriarch", "The Reaper's Toll", "The Redeemer",
  "The Rising Sun", "The Salamander", "The Scalper", "The Spirit Shroud",
  "The Squire", "The Stone of Jordan", "The Tannr Gorerod", "The Third Eye",
  "The Veinpiercer", "The Vile Husk", "The Ward", "Thundergod's Vigor",
  "Thunderstroke", "Tiamat's Rebuke", "Tides of Time", "Time Dilation",
  "Titan's Grip", "Titan's Revenge", "Todesfaelle Flamme", "Tomb Reaver",
  "Tombsong", "Toothrow", "Torch of Iro", "Transcendent Mind",
  "Treads of Cthon", "True Silver", "Twilight's Reflection", "Twitchthroe",
  "Tyrael's Might", "Uldyssian's Awakening", "Umbral Disk", "Ume's Lament",
  "Undead Crown", "Ursa's Nightmare", "Valkyrie Wing", "Vampire Gaze",
  "Veil of Steel", "Venom Grip", "Venom Ward", "Venomous Spindle",
  "Verdungo's Hearty Cord", "Viperfork", "Visceratuant", "Voices",
  "Wake of Destruction", "Wall of the Eyeless", "War Traveler", "Warlord of Blood",
  "Warlord's Trust", "Warpspear", "Warshrike", "Waterwalk",
  "Whispering Mirage", "Whispering Skull", "Widespread Destruction", "Widowmaker",
  "Wildspeaker", "Windforce", "Windhammer", "Wisp Projector",
  "Witchwild String", "Witherstring", "Wizardspike", "Wizendraw",
  "Woestave", "Wolfhowl", "Wormskull", "Wraith Flight",
  "Wraithskin", "Zakarum's Hand", "Zerae's Resolve", "Zhar's Sanctum"
] as const;

export const STATIC_HELLFORGED_UNIQUE_ITEMS = [
  "Hellforged Andariel's Visage", "Hellforged Arachnid Mesh", "Hellforged Atma's Scarab", "Hellforged Azurewrath",
  "Hellforged Blackoak Shield", "Hellforged Bonehew", "Hellforged Bul-Katho's Wedding Band", "Hellforged Crackleshot",
  "Hellforged Darkforce Spawn", "Hellforged Death's Web", "Hellforged Griffon's Eye", "Hellforged Harlequin Crest",
  "Hellforged Headhunter", "Hellforged Hellslayer", "Hellforged Herald of Zakarum", "Hellforged Jade Talon",
  "Hellforged Mara's Kaleidoscope", "Hellforged Medusa's Gaze", "Hellforged Metalgrid", "Hellforged Occultist",
  "Hellforged Rathma's Stygian Hand", "Hellforged Seraph's Hymn", "Hellforged Spirit Ward", "Hellforged Steel Carapace",
  "Hellforged Steelrend", "Hellforged Stone of Jordan", "Hellforged The Rising Sun", "Hellforged Tyrael's Might",
  "Hellforged Widespread Destruction", "Hellforged Widowmaker", "Hellforged Zerae's Resolve"
] as const;

export const STATIC_SET_ITEMS = [
  "Aldur's Stony Gaze", "Aldur's Deception", "Aldur's Gauntlet", "Aldur's Advance",
  "Angelic Sickle", "Angelic Mantle", "Angelic Halo", "Angelic Wings",
  "Arcanna's Sign", "Arcanna's Deathwand", "Arcanna's Head", "Arcanna's Flesh",
  "Arctic Horn", "Arctic Furs", "Arctic Binding", "Arctic Mitts",
  "Berserker's Headgear", "Berserker's Hauberk", "Berserker's Hatchet", "Bul-Kathos' Sacred Charge",
  "Bul-Kathos' Tribal Guardian", "Bul-Kathos' Death Band", "Cathan's Rule", "Cathan's Mesh",
  "Cathan's Visage", "Cathan's Sigil", "Cathan's Seal", "Civerb's Ward",
  "Civerb's Icon", "Civerb's Cudgel", "Cleglaw's Tooth", "Cleglaw's Claw",
  "Cleglaw's Pincers", "Cow King's Horns", "Cow King's Hide", "Cow King's Hoofs",
  "Death's Hand", "Death's Guard", "Death's Touch", "Griswold's Valor",
  "Griswold's Heart", "Griswolds's Redemption", "Griswold's Honor", "Dangoon's Teaching",
  "Heaven's Taebaek", "Haemosu's Adament", "Ondal's Almighty", "Hsarus' Iron Heel",
  "Hsarus' Iron Fist", "Hsarus' Iron Stay", "Hwanin's Splendor", "Hwanin's Refuge",
  "Hwanin's Seal", "Hwanin's Justice", "Immortal King's Will", "Immortal King's Soul Cage",
  "Immortal King's Detail", "Immortal King's Forge", "Immortal King's Pillar", "Immortal King's Stone Crusher",
  "Infernal Cranium", "Infernal Spire", "Infernal Sign", "Iratha's Collar",
  "Iratha's Cuff", "Iratha's Coil", "Iratha's Cord", "Isenhart's Lightbrand",
  "Isenhart's Parry", "Isenhart's Case", "Isenhart's Horns", "M'avina's True Sight",
  "M'avina's Embrace", "M'avina's Icy Clutch", "M'avina's Tenet", "M'avina's Caster",
  "McAuley's Paragon", "McAuley's Riprap", "McAuley's Taboo", "McAuley's Superstition",
  "Milabrega's Orb", "Milabrega's Rod", "Milabrega's Diadem", "Milabrega's Robe",
  "Naj's Puzzler", "Naj's Light Plate", "Naj's Circlet", "Natalya's Totem",
  "Natalya's Mark", "Natalya's Shadow", "Natalya's Soul", "Guillaume's Face",
  "Wilhelm's Pride", "Magnus' Skin", "Wihtstan's Guard", "Sazabi's Cobalt Redeemer",
  "Sazabi's Ghost Liberator", "Sazabi's Mental Sheath", "Sigon's Gage", "Sigon's Visor",
  "Sigon's Shelter", "Sigon's Sabot", "Sigon's Wrap", "Sigon's Guard",
  "Tal Rasha's Fire-Spun Cloth", "Tal Rasha's Adjudication", "Tal Rasha's Lidless Eye", "Tal Rasha's Howling Wind",
  "Tal Rasha's Horadric Crest", "Tancred's Crowbill", "Tancred's Spine", "Tancred's Hobnails",
  "Tancred's Weird", "Tancred's Skull", "Telling of Beads", "Laying of Hands",
  "Rite of Passage", "Spiritual Custodian", "Credendum", "Trang-Oul's Guise",
  "Trang-Oul's Scales", "Trang-Oul's Wing", "Trang-Oul's Claws", "Trang-Oul's Girth",
  "Vidala's Barb", "Vidala's Fetlock", "Vidala's Ambush", "Vidala's Snare"
] as const;

export const STATIC_RELIC_ITEMS = [] as const;
